# Generated by Django 4.2.7 on 2026-04-04 21:18

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('mining', 'Mining & Extraction'), ('construction', 'Commercial Construction'), ('manufacturing', 'Industrial Manufacturing'), ('agriculture', 'Large Scale Agriculture'), ('infrastructure', 'Infrastructure & Transport'), ('energy', 'Energy & Power Generation'), ('tourism', 'Tourism & Conservation'), ('other', 'Other Sector')], max_length=100)),
                ('status', models.CharField(choices=[('scoping', 'Scoping & Screening'), ('baseline', 'Baseline Extraction'), ('assessment', 'Impact Assessment'), ('review', 'Review & Community'), ('submitted', 'Submitted to NEMA'), ('approved', 'Approved - Licensed'), ('monitoring', 'Post-Approval Monitoring')], default='scoping', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('nema_ref', models.CharField(blank=True, max_length=100)),
                ('public_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('scale_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lead_consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-updated_at'],
            },
        ),
    ]
