# Generated by Django 4.2.7 on 2026-04-10 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nema_category',
            field=models.CharField(choices=[('low', 'Low Risk (SPR Required)'), ('medium', 'Medium Risk (SPR/CPR Required)'), ('high', 'High Risk (Full EIA Study Required)')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='proponent_id_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='proponent_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='proponent_pin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='scale_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantitative scale (e.g. bed capacity, units, hectares)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='tenant_id',
            field=models.UUIDField(),
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('file', models.ImageField(upload_to='projects/evidence/%Y/%m/%d/')),
                ('section_id', models.CharField(choices=[('site', 'General Site Photo'), ('baseline', 'Chapter 6: Baseline Evidence'), ('participation', 'Chapter 8: Public Participation'), ('impacts', 'Chapter 9: Impact Specific'), ('mitigation', 'Chapter 11: Mitigation Evidence'), ('other', 'Annex Only')], default='site', max_length=50)),
                ('caption', models.TextField(blank=True, help_text='Figure caption for the report.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Media',
                'verbose_name_plural': 'Project Media',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('file', models.FileField(upload_to='projects/documents/%Y/%m/%d/')),
                ('doc_type', models.CharField(choices=[('title_deed', 'Proof of Land Ownership (Title Deed)'), ('kra_pin', 'KRA PIN Certificate (Proponent)'), ('expert_license', 'Lead Expert Practicing License'), ('firm_registration', 'Firm of Experts Registration'), ('lab_results', 'Laboratory Analysis Certificate'), ('tor_approval', 'NEMA ToR Approval Letter'), ('other', 'General Statutory Attachment')], max_length=50)),
                ('reference_no', models.CharField(blank=True, help_text='e.g. Title LR No, License No', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Document',
                'verbose_name_plural': 'Project Documents',
                'ordering': ['doc_type'],
            },
        ),
    ]
