# Generated by Django 6.0.4 on 2026-05-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_nema_category_project_proponent_id_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('agriculture', 'Agriculture & Forestry'), ('borehole', 'Borehole Project'), ('construction', 'Urban & Housing Development'), ('energy', 'Energy & Power Generation'), ('health_facilities', 'Health & Medical Facilities'), ('infrastructure', 'Infrastructure & Transport'), ('manufacturing', 'Industrial Manufacturing'), ('mining', 'Mining & Extraction'), ('tourism', 'Tourism & Conservation'), ('waste_management', 'Waste Management & Disposal'), ('water_resources', 'Water Resources & Dams'), ('other', 'Other Sector')], max_length=100),
        ),
    ]
