# Generated by Django 4.2.7 on 2026-04-04 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('event_type', models.CharField(max_length=100)),
                ('data_hash', models.CharField(max_length=256)),
                ('tx_hash', models.CharField(blank=True, max_length=256)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Transaction'), ('confirmed', 'Confirmed On-Chain'), ('failed', 'Transaction Failed')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Blockchain Audit Log',
                'verbose_name_plural': 'Blockchain Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
