# Generated by Django 4.2.7 on 2026-04-04 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('web', 'Web Portal'), ('in_person', 'In Person')], max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('raw_text', models.TextField()),
                ('translated_text', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('categories', models.JSONField(default=list)),
                ('submitter_name', models.CharField(blank=True, max_length=200)),
                ('phone_hash', models.CharField(blank=True, help_text='SHA-256 footprint securing privacy natively.', max_length=256)),
                ('community_name', models.CharField(blank=True, max_length=200)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='projects.project')),
            ],
            options={
                'verbose_name': 'Community Feedback',
                'verbose_name_plural': 'Community Feedback',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
