# Generated by Django 4.2.7 on 2026-04-10 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_nema_category_project_proponent_id_no_and_more'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('baraza_required', models.BooleanField(default=True)),
                ('baraza_status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('newspaper_notice_status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('verified', 'Verified')], default='pending', max_length=50)),
                ('radio_announcement_status', models.CharField(choices=[('pending', 'Pending'), ('aired', 'Aired')], default='pending', max_length=50)),
                ('newspaper_clipping_url', models.URLField(blank=True)),
                ('attendance_register_url', models.URLField(blank=True)),
                ('photos_url', models.URLField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participation_workflow', to='projects.project')),
            ],
            options={
                'verbose_name': 'Participation Workflow',
            },
        ),
        migrations.CreateModel(
            name='BarazaEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('date_scheduled', models.DateTimeField()),
                ('location_name', models.CharField(max_length=300)),
                ('expected_attendance', models.PositiveIntegerField(default=50)),
                ('actual_attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('chief_name', models.CharField(blank=True, help_text='Local administration contact.', max_length=200)),
                ('minutes_summary', models.TextField(blank=True)),
                ('attendance_register_scan', models.FileField(blank=True, null=True, upload_to='participation/registers/')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='community.participationworkflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
