# Generated by Django 4.2.9 on 2026-04-10 23:25

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_participationworkflow_barazaevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='barazaevent',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, help_text='Unique token for public QR check-in.'),
        ),
    ]
