# Generated by Django 6.0.4 on 2026-04-18 05:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_barazaevent_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barazaevent',
            name='chief_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='barazaevent',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token embedded in the QR code for digital attendance check-in.', unique=True),
        ),
        migrations.AlterField(
            model_name='communityfeedback',
            name='phone_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
