# Generated by Django 4.2.7 on 2026-04-04 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EIAReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('version', models.IntegerField(default=1)),
                ('format', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document')], max_length=20)),
                ('jurisdiction', models.CharField(default='NEMA_Kenya', max_length=100)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('s3_url', models.URLField(blank=True, max_length=1000)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=256)),
                ('blockchain_tx', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
            options={
                'verbose_name': 'EIA Report',
                'verbose_name_plural': 'EIA Reports',
                'ordering': ['-generated_at', '-version'],
                'unique_together': {('project', 'version', 'format')},
            },
        ),
    ]
