# Generated by Django 4.2.7 on 2026-04-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eiareport',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eiareport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('failed', 'Failed'), ('compliance_blocked', 'Compliance Blocked')], default='draft', max_length=50),
        ),
    ]
