# Generated by Django 4.2.7 on 2026-04-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_eiareport_error_message_alter_eiareport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eiareport',
            name='s3_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
