# Generated by Django 4.2.7 on 2026-04-10 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_nema_category_project_proponent_id_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_alter_eiareport_s3_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eiareport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eiareport',
            name='expert_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eiareport',
            name='expert_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eiareport',
            name='expert_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eiareport',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='eiareport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('pending_expert_review', 'Pending Expert Review'), ('ready_for_submission', 'Ready For Submission'), ('submitted', 'Submitted'), ('failed', 'Failed'), ('compliance_blocked', 'Compliance Blocked')], default='draft', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='eiareport',
            unique_together={('project', 'version', 'format', 'language')},
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('section_id', models.CharField(help_text='Slug for the section (e.g. methodology, legal).', max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ai_suggested', 'AI Suggested'), ('expert_manual', 'Expert Manual Override'), ('review_required', 'Review Required')], default='ai_suggested', max_length=50)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.project')),
            ],
            options={
                'verbose_name': 'Report Section',
                'verbose_name_plural': 'Report Sections',
                'unique_together': {('project', 'section_id')},
            },
        ),
    ]
