# Generated by Django 4.2.9 on 2026-04-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_eiareport_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eiareport',
            name='compliance_grade',
            field=models.CharField(blank=True, null=True, help_text='A/B/C/D/F grade corresponding to compliance_score.', max_length=2),
        ),
        migrations.AddField(
            model_name='eiareport',
            name='compliance_score',
            field=models.FloatField(blank=True, help_text='Percentage score out of 100.', null=True),
        ),
        migrations.AddField(
            model_name='eiareport',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, help_text='30-day statutory review deadline.', null=True),
        ),
        migrations.AddField(
            model_name='eiareport',
            name='submission_ref',
            field=models.CharField(blank=True, default='', help_text='NEMA submission reference code.', max_length=100),
        ),
        migrations.AddField(
            model_name='eiareport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of NEMA submission.', null=True),
        ),
    ]
