# Generated by Django 6.0.4 on 2026-04-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_add_compliance_score_submission_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eiareport',
            name='compliance_grade',
            field=models.CharField(blank=True, help_text='A/B/C/D/F grade corresponding to compliance_score', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='eiareport',
            name='compliance_score',
            field=models.FloatField(blank=True, help_text='0–100 compliance score from the last audit run', null=True),
        ),
        migrations.AlterField(
            model_name='eiareport',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, help_text='30-day review deadline from submitted_at', null=True),
        ),
        migrations.AlterField(
            model_name='eiareport',
            name='submission_ref',
            field=models.CharField(blank=True, help_text='NEMA acknowledgement reference number', max_length=100),
        ),
        migrations.AlterField(
            model_name='eiareport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
