# Generated by Django 4.2.7 on 2026-04-04 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('satellite_data', models.JSONField(blank=True, null=True)),
                ('ndvi_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('hydrology_data', models.JSONField(blank=True, null=True)),
                ('soil_data', models.JSONField(blank=True, null=True)),
                ('biodiversity_data', models.JSONField(blank=True, null=True)),
                ('air_quality_baseline', models.JSONField(blank=True, null=True)),
                ('sensitivity_scores', models.JSONField(default=dict)),
                ('data_sources', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('error_log', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(help_text='The project this baseline belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='projects.project')),
            ],
            options={
                'verbose_name': 'Baseline Report',
                'verbose_name_plural': 'Baseline Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
