# Generated by Django 4.2.7 on 2026-04-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0002_add_climate_topography_noise_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselinereport',
            name='air_quality_baseline',
            field=models.JSONField(blank=True, help_text='OpenWeather: AQI, pollutants, WHO limits', null=True),
        ),
        migrations.AlterField(
            model_name='baselinereport',
            name='biodiversity_data',
            field=models.JSONField(blank=True, help_text='GBIF: species, IUCN status, taxonomy, diversity index', null=True),
        ),
        migrations.AlterField(
            model_name='baselinereport',
            name='hydrology_data',
            field=models.JSONField(blank=True, help_text='Overpass: rivers, lakes, wetlands, proximity', null=True),
        ),
        migrations.AlterField(
            model_name='baselinereport',
            name='noise_data',
            field=models.JSONField(blank=True, help_text='Noise baseline — populated from IoT sensors or manual input', null=True),
        ),
        migrations.AlterField(
            model_name='baselinereport',
            name='satellite_data',
            field=models.JSONField(blank=True, help_text='GEE: NDVI, land cover, tree cover', null=True),
        ),
        migrations.AlterField(
            model_name='baselinereport',
            name='soil_data',
            field=models.JSONField(blank=True, help_text='SoilGrids: pH, carbon, texture, erosion risk', null=True),
        ),
    ]
