# Generated by Django 6.0.4 on 2026-05-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmeasurement',
            name='equipment_used',
            field=models.CharField(blank=True, help_text='e.g. Extech SL130 Sound Meter', max_length=150),
        ),
        migrations.AlterField(
            model_name='publicnotice',
            name='notice_end_date',
            field=models.DateField(blank=True, help_text='Auto-set to publication_date + 21 days', null=True),
        ),
        migrations.AlterField(
            model_name='publicnotice',
            name='public_code',
            field=models.CharField(blank=True, help_text='e.g. EIA-NBI-2025-0042', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='publicsubmission',
            name='language',
            field=models.CharField(default='en', help_text='en or sw', max_length=10),
        ),
        migrations.AlterField(
            model_name='publicsubmission',
            name='submission_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of content + timestamp', max_length=64),
        ),
        migrations.AlterField(
            model_name='publicsubmission',
            name='submitter_location',
            field=models.CharField(blank=True, help_text='Village/Ward/Estate', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitephoto',
            name='direction_degrees',
            field=models.IntegerField(blank=True, help_text='Camera bearing 0-359°', null=True),
        ),
    ]
