# Generated by Django 6.0.4 on 2026-08-17

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('victim_name', models.CharField(blank=True, max_length=255)),
                ('victim_role', models.CharField(blank=True, max_length=255)),
                ('is_osha_recordable', models.BooleanField(default=False)),
                ('dosh_kmpdb_no', models.CharField(blank=True, max_length=100)),
                ('medical_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transport_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo_evidence', models.FileField(blank=True, null=True, upload_to='incidents/photos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='projects.project')),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
    ]
