# Generated by Django 6.0.4 on 2026-05-03 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('completed', 'Payment Received'), ('failed', 'Transaction Failed'), ('reversed', 'Payment Reversed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('credit', 'Platform Credit (Demo)')], default='mpesa', max_length=20)),
                ('provider_reference', models.CharField(blank=True, help_text='M-Pesa Receipt Number or Stripe ID', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Payer phone number for M-Pesa STK Push', max_length=20)),
                ('credits_purchased', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
