# Generated by Django 4.2.7 on 2026-04-04 21:18

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTSensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('sensor_type', models.CharField(choices=[('air', 'Air Quality'), ('water', 'Water Quality'), ('noise', 'Noise Levels'), ('soil', 'Soil Integity'), ('dust', 'Particulate Dust')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='projects.project')),
            ],
            options={
                'verbose_name': 'IoT Sensor',
                'verbose_name_plural': 'IoT Sensors',
            },
        ),
        migrations.CreateModel(
            name='EMPTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('breached', 'Breached')], default='pending', max_length=50)),
                ('kpi_metric', models.CharField(max_length=200)),
                ('kpi_threshold', models.DecimalField(decimal_places=3, max_digits=10)),
                ('kpi_unit', models.CharField(max_length=50)),
                ('mitigation_source', models.CharField(blank=True, max_length=100)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'EMP Task',
                'verbose_name_plural': 'EMP Tasks',
                'ordering': ['due_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('emp_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.emptask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.iotsensor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IoTReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('recorded_at', models.DateTimeField()),
                ('is_breach', models.BooleanField(default=False)),
                ('breach_threshold', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='emp.iotsensor')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['sensor', 'recorded_at'], name='emp_iotread_sensor__b6bc0e_idx')],
            },
        ),
    ]
