# Generated by Django 4.2.7 on 2026-04-04 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant identifier for multi-tenant isolation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('regulation_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('inapplicable', 'Inapplicable')], max_length=20)),
                ('evidence', models.TextField()),
                ('remedy', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_runs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Compliance Result',
                'verbose_name_plural': 'Compliance Results',
                'ordering': ['-checked_at'],
            },
        ),
    ]
