# Generated by Django 4.2.7 on 2026-04-04 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organisation name.', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier.', max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', help_text='Subscription plan.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant account is active.')),
                ('nema_id', models.CharField(blank=True, help_text='NEMA registration identifier (if applicable).', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of the invitee.', max_length=254)),
                ('role', models.CharField(choices=[('consultant', 'Consultant'), ('developer', 'Developer'), ('regulator', 'Regulator'), ('admin', 'Admin'), ('nema_regulator', 'NEMA Regulator')], default='consultant', help_text='Role assigned to the invitee upon registration.', max_length=50)),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Unique invitation token (sent via email link).', unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this invitation expires (48 hours after creation).')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this invitation has been used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(help_text='Tenant the invitee will join.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'User Invitation',
                'verbose_name_plural': 'User Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address (used for login).', max_length=254, unique=True)),
                ('full_name', models.CharField(help_text="User's full name.", max_length=200)),
                ('role', models.CharField(choices=[('consultant', 'Consultant'), ('developer', 'Developer'), ('regulator', 'Regulator'), ('admin', 'Admin'), ('nema_regulator', 'NEMA Regulator')], default='consultant', help_text='User role for access control.', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='Phone number (for SMS/WhatsApp notifications).', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user account is active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether this user can access the Django admin.')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='When the user account was created.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this user belongs to. Null for NEMA superusers.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
