# Generated by Django 4.2.7 on 2026-04-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expert_rank',
            field=models.CharField(choices=[('lead', 'Lead EIA/EA Expert'), ('associate', 'Associate EIA/EA Expert'), ('support', 'Support/Researcher')], default='associate', help_text='NEMA registration rank for signing authority.', max_length=50),
        ),
    ]
