# Generated by Django 6.0.4 on 2026-05-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_expert_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_status',
            field=models.CharField(choices=[('trialing', 'Trial Mode'), ('active', 'Active/Paid'), ('past_due', 'Payment Required')], default='trialing', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='credits_remaining',
            field=models.IntegerField(default=3, help_text='Number of free reports remaining for this tenant.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Whether this tenant has a premium subscription.'),
        ),
        migrations.AddField(
            model_name='user',
            name='digital_signature',
            field=models.ImageField(blank=True, help_text='Uploaded digital signature image.', null=True, upload_to='experts/signatures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='digital_stamp',
            field=models.ImageField(blank=True, help_text='Uploaded official NEMA practicing stamp image.', null=True, upload_to='experts/stamps/'),
        ),
        migrations.AddField(
            model_name='user',
            name='nema_registration_no',
            field=models.CharField(blank=True, help_text='Official NEMA registration number (e.g. NEMA/EIA/ER/1542).', max_length=100, null=True),
        ),
    ]
