# Generated by Django 4.2.7 on 2026-09-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenant_billing_status_tenant_credits_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='brand_color',
            field=models.CharField(default='#059669', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='firm_logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='firm_registration_number',
            field=models.CharField(blank=True, help_text='NEMA Firm of Experts Registration No.', max_length=50),
        ),
    ]
